'use client';
import { useEffect,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { getProject,getImagesByProject,saveImage,updateProject } from '@/lib/db';
import { generateCharacterPrompt } from '@/lib/promptGenerator';
import type { Project } from '@/types/project';

const fields:[keyof Project['character'],string][]=[['name','キャラクター名'],['type','種類'],['personality','性格'],['appearance','外見'],['clothing','服装'],['mainColor','メインカラー'],['artStyle','画風'],['features','特徴'],['negativePrompt','NG条件']];
export default function CharacterPage(){
 const{id}=useParams<{id:string}>();const router=useRouter();const[p,setP]=useState<Project|null>(null);const[prompt,setPrompt]=useState('');const[preview,setPreview]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 useEffect(()=>{Promise.all([getProject(id),getImagesByProject(id)]).then(([project,images])=>{if(!project){setErr('プロジェクトが見つかりません。');return;}setP(project);const image=images.filter(x=>x.type==='character').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(image)setPreview(URL.createObjectURL(image.blob));}).catch(()=>setErr('データを読み込めませんでした。'));},[id]);
 if(!p)return <main className="mx-auto max-w-md p-5">{err||'読み込み中...'}</main>;
 const change=(k:keyof Project['character'],v:string)=>setP({...p,character:{...p.character,[k]:v}});
 const save=async()=>{const saved=await updateProject(p);setP(saved);return saved;};
 const make=async()=>{try{const saved=await save();setPrompt(generateCharacterPrompt(saved));setMsg('キャラクター生成プロンプトを作成しました。');}catch{setErr('保存に失敗しました。');}};
 const copy=async()=>{try{await navigator.clipboard.writeText(prompt);setMsg('コピーしました。');}catch{setErr('コピーできませんでした。');}};
 const upload=async(file?:File)=>{if(!file)return;try{const bitmap=await createImageBitmap(file);await saveImage({id:crypto.randomUUID(),projectId:id,type:'character',blob:file,mimeType:file.type||'image/png',width:bitmap.width,height:bitmap.height,createdAt:new Date().toISOString()});bitmap.close();if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));setMsg('キャラクター画像を登録しました。STEP 3のスタンプ作成でこの画像を基準として使用します。');}catch{setErr('画像を保存できませんでした。別の画像をお試しください。');}};
 const next=async()=>{try{await updateProject({...p,currentStep:Math.max(p.currentStep,3)});router.push(`/projects/${id}/stamps`);}catch{setErr('保存に失敗しました。');}};
 return <main className="mx-auto min-h-dvh max-w-md bg-zinc-50 px-5 pb-[calc(env(safe-area-inset-bottom)+2rem)] pt-[calc(env(safe-area-inset-top)+1rem)]"><button onClick={()=>router.push(`/projects/${id}/idea`)} className="min-h-11 text-2xl">‹</button><p className="mt-2 text-xs font-bold text-emerald-600">STEP 2 / 5</p><h1 className="text-2xl font-bold">キャラクター</h1>{err&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{err}</p>}{msg&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</p>}<section className="mt-6 space-y-4 rounded-3xl border bg-white p-5">{fields.map(([k,label])=><label key={k} className="block text-sm font-medium">{label}<textarea rows={k==='features'||k==='negativePrompt'?3:1} value={p.character[k]} onChange={e=>change(k,e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none"/></label>)}<button onClick={make} className="min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white">キャラクター生成プロンプトを作成</button></section>{prompt&&<section className="mt-6 rounded-3xl bg-emerald-50 p-5"><div className="flex justify-between"><b>AI用プロンプト</b><button onClick={copy} className="min-h-11 rounded-xl border bg-white px-4 text-sm font-bold text-emerald-700">コピー</button></div><pre className="mt-3 whitespace-pre-wrap text-sm leading-6">{prompt}</pre></section>}<section className="mt-6 rounded-3xl border bg-white p-5"><h2 className="font-bold">キャラクター画像を登録</h2><p className="mt-1 text-xs leading-5 text-zinc-500">外部AIで生成したキャラクター画像を登録してください。この画像をSTEP 3の3×3スタンプ画像を作るときの基準キャラクターとして使用します。</p>{preview&&<img src={preview} alt="キャラクタープレビュー" className="mt-4 aspect-square w-full rounded-2xl bg-zinc-100 object-contain"/>}<label className="mt-4 flex min-h-12 cursor-pointer items-center justify-center rounded-xl border border-emerald-600 font-bold text-emerald-700">キャラクター画像を選択<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label><button onClick={next} className="mt-4 min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white">スタンプ作成へ</button></section></main>;
}
