'use client';
import { useState } from 'react';
import Link from 'next/link';
import { createBackup, downloadBackup, restoreBackup } from '@/lib/backup';

export default function SettingsPage(){
  const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  const exportBackup=async()=>{setBusy(true);setErr('');try{const blob=await createBackup();const date=new Date().toISOString().slice(0,10);downloadBackup(blob,`line-stamp-maker-backup-${date}.json`);setMsg('バックアップを書き出しました。iPhoneの「ファイル」に保存してください。');}catch{setErr('バックアップの作成に失敗しました。');}finally{setBusy(false);}};
  const restore=async(file?:File)=>{if(!file)return;if(!window.confirm('バックアップ内容をこの端末へ復元します。既存IDと同じデータは上書きされます。続けますか？'))return;setBusy(true);setErr('');try{const result=await restoreBackup(file);setMsg(`復元しました。プロジェクト${result.projects}件、画像${result.images}件です。`);}catch(e){setErr(e instanceof Error?e.message:'バックアップの復元に失敗しました。');}finally{setBusy(false);}};
  return <main className="mx-auto min-h-dvh max-w-md bg-zinc-50 px-5 pb-[calc(env(safe-area-inset-bottom)+2rem)] pt-[calc(env(safe-area-inset-top)+1rem)]"><div className="flex items-center justify-between"><Link href="/" className="flex min-h-11 min-w-11 items-center text-2xl">‹</Link><h1 className="text-xl font-bold">設定</h1><span className="w-11"/></div><p className="mt-3 text-sm leading-6 text-zinc-500">プロジェクトと画像はこのiPhoneのブラウザ内に保存されています。端末変更やSafariデータ削除に備えて、定期的にバックアップしてください。</p>{err&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{err}</p>}{msg&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</p>}<section className="mt-6 rounded-3xl border bg-white p-5"><h2 className="font-bold">iPhoneのホーム画面に追加</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Safariでこのアプリを開き、共有ボタン →「ホーム画面に追加」を選ぶと、アプリのように全画面で起動できます。プロジェクトデータはPWAキャッシュではなくIndexedDBへ保存されます。</p><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-900">おすすめ：普段はホーム画面から使い、節目ごとにバックアップを書き出してください。</div></section><section className="mt-6 rounded-3xl border bg-white p-5"><h2 className="font-bold">バックアップを書き出す</h2><p className="mt-2 text-xs leading-5 text-zinc-500">すべてのプロジェクト情報と画像を1つのJSONファイルにまとめます。画像は移植可能なBase64形式で含まれます。</p><button disabled={busy} onClick={exportBackup} className="mt-4 min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white">{busy?'処理中...':'バックアップを書き出す'}</button></section><section className="mt-6 rounded-3xl border bg-white p-5"><h2 className="font-bold">バックアップから復元</h2><p className="mt-2 text-xs leading-5 text-zinc-500">以前書き出したLINE Stamp MakerのバックアップJSONを選択します。</p><label className={`mt-4 flex min-h-12 cursor-pointer items-center justify-center rounded-xl border border-emerald-600 font-bold text-emerald-700 ${busy?'pointer-events-none opacity-40':''}`}>バックアップファイルを選択<input type="file" accept="application/json,.json" className="hidden" onChange={e=>restore(e.target.files?.[0])}/></label></section><section className="mt-6 rounded-3xl bg-amber-50 p-5 text-sm leading-6 text-amber-900"><b>大切な注意</b><br/>PWAのキャッシュとプロジェクトデータは別物です。アプリをホーム画面に追加していても、SafariのWebサイトデータを削除するとIndexedDBのデータが消える可能性があります。</section></main>;
}
